# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booknovalue', models.PositiveIntegerField(blank=True)),
                ('bookdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField(max_length=200, null=True)),
                ('brand_pic', models.ImageField(default='default.png', upload_to='images/brandpics')),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('glass_pic', models.ImageField(default='brandpics/default.png', upload_to='brandpics/')),
                ('detail', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('price', models.PositiveIntegerField(blank=True)),
                ('booker', models.ManyToManyField(blank=True, through='catalog.booking', to=settings.AUTH_USER_MODEL)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='GlassInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Glass.', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('glass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Glass')),
            ],
            options={
                'ordering': ['id'],
                'permissions': (('can_mark_returned', 'Set book as returned'),),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='glass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Glass'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
