# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='glass',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=25, max_digits=8),
            preserve_default=False,
        ),
    ]
