# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='imagepic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.TextField()),
                ('filename', models.CharField(max_length=255)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='glass',
            name='glass_pic',
            field=models.ImageField(blank=True, null=True, upload_to='catalog.imagepic/bytes/filename/mimetype'),
        ),
    ]
