# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170603_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepic',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Glass'),
        ),
    ]
