# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_glass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='price',
            field=models.PositiveIntegerField(blank=True, max_length=5),
        ),
    ]
