# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170319_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknocount',
            name='booknovalue',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
