# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_imagepic_glass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepic',
            name='glass',
        ),
    ]
