# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_remove_imagepic_glass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderno', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_pic',
            field=models.ImageField(blank=True, null=True, upload_to='catalog.imagepic/bytes/filename/mimetype'),
        ),
        migrations.AlterField(
            model_name='glass',
            name='glass_pic',
            field=models.FileField(blank=True, null=True, upload_to='catalog.imagepic/bytes/filename/mimetype'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Glass'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orderuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Order'),
        ),
    ]
