# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170319_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glass',
            name='price',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='glassinstance',
            name='glass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Glass'),
        ),
    ]
