# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170322_1907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='glass',
            old_name='summary',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='last_name',
        ),
    ]
