# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='contact',
            field=models.TextField(blank=True, null=True),
        ),
    ]
