# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170325_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='summary',
            new_name='detail',
        ),
    ]
