# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20170325_1157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booknocount',
            new_name='booking',
        ),
    ]
