# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_userdetail_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
